properties:
  addonManagerNamespace:
    type: string
  fullnameOverride:
    type: string
  helm:
    properties:
      createNamespace:
        type: boolean
      releases:
        additionalProperties:
          properties:
            enabled:
              type: boolean
            values:
              type: object
              x-kubernetes-preserve-unknown-fields: true
            version:
              type: string
          required:
          - enabled
          - version
          type: object
        type: object
      repositories:
        additionalProperties:
          properties:
            interval:
              pattern: ^([0-9]+(\.[0-9]+)?(ms|s|m|h))+$
              type: string
            provider:
              default: generic
              enum:
              - generic
              - aws
              - azure
              - gcp
              type: string
            secretName:
              type: string
            timeout:
              type: string
            type:
              enum:
              - default
              - oci
              type: string
            url:
              type: string
          required:
          - url
          type: object
        type: object
    required:
    - createNamespace
    - releases
    - repositories
    type: object
  image:
    properties:
      proxies:
        properties:
          appscode:
            type: string
          dockerHub:
            type: string
          dockerLibrary:
            type: string
          ghcr:
            type: string
          kubernetes:
            type: string
          microsoft:
            type: string
          quay:
            type: string
        type: object
    type: object
  kubeconfigSecretName:
    type: string
  kubectl:
    properties:
      image:
        type: string
    required:
    - image
    type: object
  manager:
    properties:
      env:
        items:
          properties:
            name:
              type: string
            value:
              type: string
            valueFrom:
              properties:
                configMapKeyRef:
                  properties:
                    key:
                      type: string
                    name:
                      default: ''
                      type: string
                    optional:
                      type: boolean
                  required:
                  - key
                  type: object
                  x-kubernetes-map-type: atomic
                fieldRef:
                  properties:
                    apiVersion:
                      type: string
                    fieldPath:
                      type: string
                  required:
                  - fieldPath
                  type: object
                  x-kubernetes-map-type: atomic
                resourceFieldRef:
                  properties:
                    containerName:
                      type: string
                    divisor:
                      anyOf:
                      - type: integer
                      - type: string
                      pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                      x-kubernetes-int-or-string: true
                    resource:
                      type: string
                  required:
                  - resource
                  type: object
                  x-kubernetes-map-type: atomic
                secretKeyRef:
                  properties:
                    key:
                      type: string
                    name:
                      default: ''
                      type: string
                    optional:
                      type: boolean
                  required:
                  - key
                  type: object
                  x-kubernetes-map-type: atomic
              type: object
          required:
          - name
          type: object
        type: array
        x-kubernetes-list-map-keys:
        - name
        x-kubernetes-list-type: map
      envFrom:
        items:
          properties:
            configMapRef:
              properties:
                name:
                  default: ''
                  type: string
                optional:
                  type: boolean
              type: object
              x-kubernetes-map-type: atomic
            prefix:
              type: string
            secretRef:
              properties:
                name:
                  default: ''
                  type: string
                optional:
                  type: boolean
              type: object
              x-kubernetes-map-type: atomic
          type: object
        type: array
        x-kubernetes-list-type: atomic
      image:
        type: string
      imagePullPolicy:
        type: string
      securityContext:
        properties:
          allowPrivilegeEscalation:
            type: boolean
          appArmorProfile:
            properties:
              localhostProfile:
                type: string
              type:
                type: string
            required:
            - type
            type: object
          capabilities:
            properties:
              add:
                items:
                  type: string
                type: array
                x-kubernetes-list-type: atomic
              drop:
                items:
                  type: string
                type: array
                x-kubernetes-list-type: atomic
            type: object
          privileged:
            type: boolean
          procMount:
            type: string
          readOnlyRootFilesystem:
            type: boolean
          runAsGroup:
            format: int64
            type: integer
          runAsNonRoot:
            type: boolean
          runAsUser:
            format: int64
            type: integer
          seLinuxOptions:
            properties:
              level:
                type: string
              role:
                type: string
              type:
                type: string
              user:
                type: string
            type: object
          seccompProfile:
            properties:
              localhostProfile:
                type: string
              type:
                type: string
            required:
            - type
            type: object
          windowsOptions:
            properties:
              gmsaCredentialSpec:
                type: string
              gmsaCredentialSpecName:
                type: string
              hostProcess:
                type: boolean
              runAsUserName:
                type: string
            type: object
        type: object
      tag:
        type: string
    required:
    - image
    - imagePullPolicy
    - securityContext
    type: object
  nameOverride:
    type: string
  offlineInstaller:
    type: boolean
  placement:
    properties:
      create:
        type: boolean
      name:
        type: string
    required:
    - create
    - name
    type: object
  platform:
    properties:
      baseURL:
        type: string
      caBundle:
        type: string
      token:
        type: string
    required:
    - baseURL
    type: object
  registry:
    properties:
      certs:
        additionalProperties:
          type: string
        type: object
      credentials:
        additionalProperties:
          type: string
        type: object
      imagePullSecrets:
        items:
          type: string
        type: array
    type: object
  registryFQDN:
    type: string
required:
- helm
- image
- kubectl
- manager
- placement
- platform
- registry
- registryFQDN
type: object
