//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterManagerHub) DeepCopyInto(out *ClusterManagerHub) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterManagerHub.
func (in *ClusterManagerHub) DeepCopy() *ClusterManagerHub {
	if in == nil {
		return nil
	}
	out := new(ClusterManagerHub)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterManagerHub) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterManagerHubList) DeepCopyInto(out *ClusterManagerHubList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterManagerHub, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterManagerHubList.
func (in *ClusterManagerHubList) DeepCopy() *ClusterManagerHubList {
	if in == nil {
		return nil
	}
	out := new(ClusterManagerHubList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterManagerHubList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterManagerHubSpec) DeepCopyInto(out *ClusterManagerHubSpec) {
	*out = *in
	out.Hub = in.Hub
	out.BundleVersion = in.BundleVersion
	if in.RegistrationFeatures != nil {
		in, out := &in.RegistrationFeatures, &out.RegistrationFeatures
		*out = make([]FeatureGate, len(*in))
		copy(*out, *in)
	}
	if in.WorkFeatures != nil {
		in, out := &in.WorkFeatures, &out.WorkFeatures
		*out = make([]FeatureGate, len(*in))
		copy(*out, *in)
	}
	if in.AddonFeatures != nil {
		in, out := &in.AddonFeatures, &out.AddonFeatures
		*out = make([]FeatureGate, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterManagerHubSpec.
func (in *ClusterManagerHubSpec) DeepCopy() *ClusterManagerHubSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterManagerHubSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterManagerSpoke) DeepCopyInto(out *ClusterManagerSpoke) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterManagerSpoke.
func (in *ClusterManagerSpoke) DeepCopy() *ClusterManagerSpoke {
	if in == nil {
		return nil
	}
	out := new(ClusterManagerSpoke)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterManagerSpoke) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterManagerSpokeList) DeepCopyInto(out *ClusterManagerSpokeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterManagerSpoke, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterManagerSpokeList.
func (in *ClusterManagerSpokeList) DeepCopy() *ClusterManagerSpokeList {
	if in == nil {
		return nil
	}
	out := new(ClusterManagerSpokeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterManagerSpokeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterManagerSpokeSpec) DeepCopyInto(out *ClusterManagerSpokeSpec) {
	*out = *in
	out.Hub = in.Hub
	out.Klusterlet = in.Klusterlet
	out.BundleVersion = in.BundleVersion
	if in.RegistrationFeatures != nil {
		in, out := &in.RegistrationFeatures, &out.RegistrationFeatures
		*out = make([]FeatureGate, len(*in))
		copy(*out, *in)
	}
	if in.WorkFeatures != nil {
		in, out := &in.WorkFeatures, &out.WorkFeatures
		*out = make([]FeatureGate, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterManagerSpokeSpec.
func (in *ClusterManagerSpokeSpec) DeepCopy() *ClusterManagerSpokeSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterManagerSpokeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FeatureGate) DeepCopyInto(out *FeatureGate) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FeatureGate.
func (in *FeatureGate) DeepCopy() *FeatureGate {
	if in == nil {
		return nil
	}
	out := new(FeatureGate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HubBundleVersion) DeepCopyInto(out *HubBundleVersion) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HubBundleVersion.
func (in *HubBundleVersion) DeepCopy() *HubBundleVersion {
	if in == nil {
		return nil
	}
	out := new(HubBundleVersion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HubInfo) DeepCopyInto(out *HubInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HubInfo.
func (in *HubInfo) DeepCopy() *HubInfo {
	if in == nil {
		return nil
	}
	out := new(HubInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Klusterlet) DeepCopyInto(out *Klusterlet) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Klusterlet.
func (in *Klusterlet) DeepCopy() *Klusterlet {
	if in == nil {
		return nil
	}
	out := new(Klusterlet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpokeBundleVersion) DeepCopyInto(out *SpokeBundleVersion) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpokeBundleVersion.
func (in *SpokeBundleVersion) DeepCopy() *SpokeBundleVersion {
	if in == nil {
		return nil
	}
	out := new(SpokeBundleVersion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpokeHub) DeepCopyInto(out *SpokeHub) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpokeHub.
func (in *SpokeHub) DeepCopy() *SpokeHub {
	if in == nil {
		return nil
	}
	out := new(SpokeHub)
	in.DeepCopyInto(out)
	return out
}
