properties:
  aws:
    properties:
      hubClusterArn:
        type: string
      managedClusterArn:
        type: string
    type: object
  bootstrap:
    type: boolean
  bundleVersion:
    properties:
      clusteradmImageVersion:
        type: string
      operatorImageVersion:
        type: string
      placementImageVersion:
        type: string
      registrationImageVersion:
        type: string
      workImageVersion:
        type: string
    type: object
  clusterMetadata:
    properties:
      name:
        type: string
      store:
        properties:
          clusterClaim:
            properties:
              name:
                default: ''
                type: string
            type: object
            x-kubernetes-map-type: atomic
          secret:
            properties:
              name:
                type: string
              namespace:
                type: string
            type: object
        required:
        - clusterClaim
        - secret
        type: object
    required:
    - name
    - store
    type: object
  clusteradm:
    properties:
      image:
        type: string
      securityContext:
        properties:
          allowPrivilegeEscalation:
            type: boolean
          appArmorProfile:
            properties:
              localhostProfile:
                type: string
              type:
                type: string
            required:
            - type
            type: object
          capabilities:
            properties:
              add:
                items:
                  type: string
                type: array
                x-kubernetes-list-type: atomic
              drop:
                items:
                  type: string
                type: array
                x-kubernetes-list-type: atomic
            type: object
          privileged:
            type: boolean
          procMount:
            type: string
          readOnlyRootFilesystem:
            type: boolean
          runAsGroup:
            format: int64
            type: integer
          runAsNonRoot:
            type: boolean
          runAsUser:
            format: int64
            type: integer
          seLinuxOptions:
            properties:
              level:
                type: string
              role:
                type: string
              type:
                type: string
              user:
                type: string
            type: object
          seccompProfile:
            properties:
              localhostProfile:
                type: string
              type:
                type: string
            required:
            - type
            type: object
          windowsOptions:
            properties:
              gmsaCredentialSpec:
                type: string
              gmsaCredentialSpecName:
                type: string
              hostProcess:
                type: boolean
              runAsUserName:
                type: string
            type: object
        type: object
    required:
    - image
    type: object
  hub:
    properties:
      apiServer:
        type: string
      caData:
        type: string
      kubeConfig:
        type: string
      token:
        type: string
    type: object
  managedKubeconfig:
    type: string
  registrationFeatures:
    items:
      properties:
        feature:
          type: string
        mode:
          default: Disable
          enum:
          - Enable
          - Disable
          type: string
      required:
      - feature
      type: object
    type: array
  registry:
    type: string
  securityContext:
    properties:
      allowPrivilegeEscalation:
        type: boolean
      appArmorProfile:
        properties:
          localhostProfile:
            type: string
          type:
            type: string
        required:
        - type
        type: object
      capabilities:
        properties:
          add:
            items:
              type: string
            type: array
            x-kubernetes-list-type: atomic
          drop:
            items:
              type: string
            type: array
            x-kubernetes-list-type: atomic
        type: object
      privileged:
        type: boolean
      procMount:
        type: string
      readOnlyRootFilesystem:
        type: boolean
      runAsGroup:
        format: int64
        type: integer
      runAsNonRoot:
        type: boolean
      runAsUser:
        format: int64
        type: integer
      seLinuxOptions:
        properties:
          level:
            type: string
          role:
            type: string
          type:
            type: string
          user:
            type: string
        type: object
      seccompProfile:
        properties:
          localhostProfile:
            type: string
          type:
            type: string
        required:
        - type
        type: object
      windowsOptions:
        properties:
          gmsaCredentialSpec:
            type: string
          gmsaCredentialSpecName:
            type: string
          hostProcess:
            type: boolean
          runAsUserName:
            type: string
        type: object
    type: object
  workFeatures:
    items:
      properties:
        feature:
          type: string
        mode:
          default: Disable
          enum:
          - Enable
          - Disable
          type: string
      required:
      - feature
      type: object
    type: array
required:
- bootstrap
- clusterMetadata
- clusteradm
type: object
