{{-if (index .Values "addons" "cluster-proxy" "enabled") }}

apiVersion: addon.open-cluster-management.io/v1alpha1
kind: ManagedClusterAddOn
metadata:
  name: cluster-proxy
  namespace: {{ .Release.Namespace }}
spec:
  installNamespace: open-cluster-management-cluster-proxy

{{- end }}
