apiVersion: v1
description: Spoke Cluster Addons
name: spoke-cluster-addons
version: v2025.8.31
appVersion: v0.0.3
home: https://github.com/kluster-manager/cluster-proxy
icon: https://cdn.appscode.com/images/products/searchlight/icons/android-icon-192x192.png
sources:
- https://github.com/kluster-manager/cluster-proxy
maintainers:
- name: appscode
  email: support@appscode.com
