properties:
  addonManagerNamespace:
    type: string
  fullnameOverride:
    type: string
  kubeconfigSecretName:
    type: string
  kubectl:
    properties:
      image:
        type: string
    required:
    - image
    type: object
  nameOverride:
    type: string
required:
- kubectl
type: object
