{{- if not .Values.kubeconfigSecretName }}

{{- $restpl := $.Files.Get "common/addon/cluster-proxy.yaml" }}
{{ tpl $restpl $ }}

{{- $restpl := $.Files.Get "common/addon/kubeslice.yaml" }}
{{ tpl $restpl $ }}

{{- end }}
