properties:
  addonFeatures:
    items:
      properties:
        feature:
          type: string
        mode:
          default: Disable
          enum:
          - Enable
          - Disable
          type: string
      required:
      - feature
      type: object
    type: array
  autoApprove:
    type: boolean
  aws:
    properties:
      hubClusterArn:
        type: string
    type: object
  bundleVersion:
    properties:
      addonManagerImageVersion:
        type: string
      operatorImageVersion:
        type: string
      placementImageVersion:
        type: string
      registrationImageVersion:
        type: string
      workImageVersion:
        type: string
    type: object
  hub:
    properties:
      registry:
        type: string
      securityContext:
        properties:
          allowPrivilegeEscalation:
            type: boolean
          appArmorProfile:
            properties:
              localhostProfile:
                type: string
              type:
                type: string
            required:
            - type
            type: object
          capabilities:
            properties:
              add:
                items:
                  type: string
                type: array
                x-kubernetes-list-type: atomic
              drop:
                items:
                  type: string
                type: array
                x-kubernetes-list-type: atomic
            type: object
          privileged:
            type: boolean
          procMount:
            type: string
          readOnlyRootFilesystem:
            type: boolean
          runAsGroup:
            format: int64
            type: integer
          runAsNonRoot:
            type: boolean
          runAsUser:
            format: int64
            type: integer
          seLinuxOptions:
            properties:
              level:
                type: string
              role:
                type: string
              type:
                type: string
              user:
                type: string
            type: object
          seccompProfile:
            properties:
              localhostProfile:
                type: string
              type:
                type: string
            required:
            - type
            type: object
          windowsOptions:
            properties:
              gmsaCredentialSpec:
                type: string
              gmsaCredentialSpecName:
                type: string
              hostProcess:
                type: boolean
              runAsUserName:
                type: string
            type: object
        type: object
      tokenID:
        type: string
      tokenSecret:
        type: string
      useBootstrapToken:
        type: boolean
    type: object
  registrationFeatures:
    items:
      properties:
        feature:
          type: string
        mode:
          default: Disable
          enum:
          - Enable
          - Disable
          type: string
      required:
      - feature
      type: object
    type: array
  workFeatures:
    items:
      properties:
        feature:
          type: string
        mode:
          default: Disable
          enum:
          - Enable
          - Disable
          type: string
      required:
      - feature
      type: object
    type: array
type: object
